### ISSUE TITLE
tcmalloc: large alloc (Killed)

### ISSUE THREAD

**Issue by TulioChiodi** [yinkalario/DCASE2019-TASK3#1]
First of all, I would like to thank you for making the code available.

I'm trying to run the code in Google Colab (after trying in my notebook and having the same problem).

While trying to run 1_extract_feature.sh, I keep getting "tcmalloc: large alloc 20529389568 bytes" and my process is killed.

The dev and eval features have been successfully extracted. But when it tries to run the fit() function the RAM starts to be consumed to its limit, which is where the error occurs. 

I'm running a Google Colaboratory instance with 25Gb RAM.

I don't know if this is the correct place to post it, so if there is another place to do it, please let me know.

Thank you,

**Comment by yinkalario** [comment]
Np. I think that may be possible. The fit() needs to load all of the train data in the first place and then calculate the scalar. You can modify it not to load all of the train data, but part of it by doing:

for hdf5_fn in os.listdir(hdf5_dir)[:5000]:

In this way, it only loads the first 5000 data to calculate the scalar, which should be enough. 5000 is just a number for your reference.

Thanks.

**Comment by TulioChiodi** [comment]
Mr. Yin Cao,

I am still having problems with memory management, now in the training phase.
More specifically, when I start the training phase my process get killed and I get some error about not having the pre-trained model iter_50000.pth. I believe that's resulting of not reaching the save model point in training phase.
Just out of curiosity, could you tell me how much RAM the computer that trained this model has?
Since I have bad notebook configuration, Im thinking about slicing the dataset to use less memory.

Thanks.

**Comment by yinkalario** [comment]
> Mr. Yin Cao,
> 
> I am still having problems with memory management, now in the training phase.
> More specifically, when I start the training phase my process get killed and I get some error about not having the pre-trained model iter_50000.pth. I believe that's resulting of not reaching the save model point in training phase.
> Just out of curiosity, could you tell me how much RAM the computer that trained this model has?
> Since I have bad notebook configuration, Im thinking about slicing the dataset to use less memory.
> 
> Thanks.

Hi Tulio,

I think that may be the reason of out of memory. I think the memory I used is 32GB. I am not sure if the GPU you used has enough memory. What you can do is to decrease the batch size to be 32 or even 16. What was the error you got?

Another thing is we are making another new version of the code to load the training data dynamically instead of pre-loading the data into memory first.

Thanks,

Yin

**Comment by TulioChiodi** [comment]
> > Mr. Yin Cao,
> > I am still having problems with memory management, now in the training phase.
> > More specifically, when I start the training phase my process get killed and I get some error about not having the pre-trained model iter_50000.pth. I believe that's resulting of not reaching the save model point in training phase.
> > Just out of curiosity, could you tell me how much RAM the computer that trained this model has?
> > Since I have bad notebook configuration, Im thinking about slicing the dataset to use less memory.
> > Thanks.
> 
> Hi Tulio,
> 
> I think that may be the reason of out of memory. I think the memory I used is 32GB. I am not sure if the GPU you used has enough memory. What you can do is to decrease the batch size to be 32 or even 16. What was the error you got?
> 
> Another thing is we are making another new version of the code to load the training data dynamically instead of pre-loading the data into memory first.
> 
> Thanks,
> 
> Yin


Hi Yin,

I realized that I had set GPU_ID to 1 and was not recognizing my GPU.
Now I'm training the model, it will take about 10 hours.
Sorry for the inconvenience and thanks for your time.

Túlio
