### ISSUE TITLE
About fold

### ISSUE THREAD

**Issue by likenneth** [yinkalario/DCASE2019-TASK3#2]
Hi, Yin! Great thanks for your sharing your code.

I tried to run your code to reproduce the result on [SELD challenge page](http://dcase.community/challenge2019/task-sound-event-localization-and-detection-results), but I got a bit confused on the fold thing. 

To get the result denoted evaluation dataset, I definitely have a submit a result file to the website. I don't want to do that now, so I understand that I could only reproduce the result on the right column, development dataset. And I wonder what configuration and workflow I need to go through after running the train.bash. 

> Is it that I need to run 3_eval.sh? But it seems that is for submission, and I must download the eval dataset for that. 
> Is it the optional_cross_validation? But I met some bugs, that is the saved pth has a name of fold is -1 in it, which does not match the queried 1-4 in the bash file. 

To fully understand your code, I want to know what the fold is. As you have said in the trian.sh, -1 means evaluation, then why you are using that to train? Further, is the result shown in tensorboard during training comparable to Challenge website dev column?

**Comment by yinkalario** [comment]
Hi ricolike,

Sorry for the late reply. Please refer to DCASE 2019 task 3. Those folds were set up by official organizers. 3_eval.sh is for submission. During training it also does cross-validation, so you can see some results there in real-time. When fold=-1, it means using all of the dev data to train without validation. That is for submission. When you need to understand the code, just ignore the case fold=-1.

Let me know if you have more questions.

Thanks,
Yin

**Comment by likenneth** [comment]
Thank you for your answering my question about fold, but I have two more question:
1. when training with fold=-1, we are not validating on part of the training data, so the result shall not be comparable to dev set performance shown on challenge website right? Is the fair way to compare with dev set performance by cross validation shell script?
2. After all, I only want to reproduce your scores in the challenge website in the dev set column, could you provide an easy way for me to do that (and I see there are a lot of file manipulation happening, could you point it out to me which file would the score be in after CV done?), currently my work flow is:

    - 2_train.sh
    - optional_cross_validation.sh

But unfortunately this does not work, there are some file not found errors thrown out during the CV process.

**Comment by yinkalario** [comment]
Sorry that I just noticed your question.

1. when training with fold=-1, it uses all development data for training, so there is no cross-validation. So you could set fold=1 to train with three folds and validation with the left fold.

2. I think if you use fold=1, you can see the validation process. To reproduce the score, you need to use fold=-1 to train with all data and evaluate it on the evaluation dataset.

You can email me @ yin.cao@surrey.ac.uk

Thanks,

Yin
